import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { approve, approvalStatus, requireAllClips, requireApproval } from '../src/human-gates.mjs';

const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'aih-gates-'));
const a = path.join(dir, 'a.txt');
const b = path.join(dir, 'b.txt');
fs.writeFileSync(a, 'one'); fs.writeFileSync(b, 'two');
assert.equal(approvalStatus(dir, 'direction', [a]).ok, false);
approve(dir, 'direction', [a]);
assert.equal(approvalStatus(dir, 'direction', [a]).ok, true);
fs.writeFileSync(a, 'changed');
assert.match(approvalStatus(dir, 'direction', [a]).reason, /失效/);
approve(dir, 'clip', [a], { id: 'g001', variant: 'preview' });
assert.equal(approvalStatus(dir, 'clip', [a], 'g001', 'preview').ok, true);
assert.equal(approvalStatus(dir, 'clip', [a], 'g001', 'final').ok, false);
approve(dir, 'clip', [b], { id: 'g001', variant: 'final' });
assert.equal(approvalStatus(dir, 'clip', [a], 'g001', 'preview').ok, true);
assert.equal(approvalStatus(dir, 'clip', [b], 'g001', 'final').ok, true);
assert.equal(approvalStatus(dir, 'clip', [a], 'g002').ok, false);
assert.throws(() => requireApproval(dir, 'keyframes', [b]), /机器检查通过只表示/);
const units = path.join(dir, 'units'); fs.mkdirSync(units);
fs.writeFileSync(path.join(units, 'g001.final.result.json'), JSON.stringify({ files: [b] }));
requireAllClips(dir, { units: [{ id: 'g001' }] });
assert.throws(() => requireAllClips(dir, { units: [{ id: 'g001' }, { id: 'g002' }] }), /正式档尚未生成/);

const legacy = fs.mkdtempSync(path.join(os.tmpdir(), 'aih-gates-legacy-'));
const legacyVideo = path.join(legacy, 'legacy.mp4');
fs.writeFileSync(legacyVideo, 'legacy');
approve(legacy, 'clip', [legacyVideo], { id: 'g001' });
const reviewFile = path.join(legacy, 'review.approvals.json');
const review = JSON.parse(fs.readFileSync(reviewFile, 'utf8'));
review.approvals.clips.g001 = review.approvals.clips.g001.final;
fs.writeFileSync(reviewFile, JSON.stringify(review));
assert.equal(approvalStatus(legacy, 'clip', [legacyVideo], 'g001', 'final').ok, true);
assert.equal(approvalStatus(legacy, 'clip', [legacyVideo], 'g001', 'preview').ok, false);
console.log('human gates: 14/14 passed');
