import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { approve, approvalStatus, clipResultPath, requireAllClips, requireApproval } from '../src/human-gates.mjs';

const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'aih-gates-'));
const a = path.join(dir, 'a.txt');
const b = path.join(dir, 'b.txt');
fs.writeFileSync(a, 'one'); fs.writeFileSync(b, 'two');
assert.equal(approvalStatus(dir, 'direction', [a]).ok, false);
approve(dir, 'direction', [a]);
assert.equal(approvalStatus(dir, 'direction', [a]).ok, true);
fs.writeFileSync(a, 'changed');
assert.match(approvalStatus(dir, 'direction', [a]).reason, /失效/);
approve(dir, 'clip', [a], { id: 'g001' });
assert.equal(approvalStatus(dir, 'clip', [a], 'g001').ok, true);
approve(dir, 'clip', [b], { id: 'g001' });
assert.equal(approvalStatus(dir, 'clip', [a], 'g001').ok, false);
assert.equal(approvalStatus(dir, 'clip', [b], 'g001').ok, true);
assert.equal(approvalStatus(dir, 'clip', [a], 'g002').ok, false);
assert.throws(() => requireApproval(dir, 'keyframes', [b]), /人工闸门未通过/);
const units = path.join(dir, 'units'); fs.mkdirSync(units);
fs.writeFileSync(path.join(units, 'g001.result.json'), JSON.stringify({ files: [b] }));
requireAllClips(dir, { units: [{ id: 'g001' }] });
assert.throws(() => requireAllClips(dir, { units: [{ id: 'g001' }, { id: 'g002' }] }), /尚未生成/);

const legacy = fs.mkdtempSync(path.join(os.tmpdir(), 'aih-gates-legacy-'));
const legacyVideo = path.join(legacy, 'legacy.mp4');
fs.writeFileSync(legacyVideo, 'legacy');
approve(legacy, 'clip', [legacyVideo], { id: 'g001' });
const reviewFile = path.join(legacy, 'review.approvals.json');
const review = JSON.parse(fs.readFileSync(reviewFile, 'utf8'));
assert.equal(approvalStatus(legacy, 'clip', [legacyVideo], 'g001').ok, true);
review.approvals.clips.g001 = { final: review.approvals.clips.g001, preview: { artifact_hash: 'old' } };
fs.writeFileSync(reviewFile, JSON.stringify(review));
assert.equal(approvalStatus(legacy, 'clip', [legacyVideo], 'g001').ok, true);
fs.mkdirSync(path.join(legacy, 'units'));
fs.writeFileSync(path.join(legacy, 'units', 'g001.final.result.json'), JSON.stringify({ files: [legacyVideo] }));
requireAllClips(legacy, { units: [{ id: 'g001' }] });
const older = path.join(legacy, 'units', 'g001.result.json');
fs.writeFileSync(older, JSON.stringify({ files: [] }));
const past = new Date(Date.now() - 60000);
fs.utimesSync(older, past, past);
assert.match(clipResultPath(legacy, 'g001'), /\.final\.result\.json$/);
requireAllClips(legacy, { units: [{ id: 'g001' }] });
const future = new Date(Date.now() + 60000);
fs.utimesSync(older, future, future);
assert.equal(clipResultPath(legacy, 'g001'), older);
assert.throws(() => requireAllClips(legacy, { units: [{ id: 'g001' }] }), /没有可审阅/);
fs.utimesSync(older, past, past);
review.approvals.clips.g001 = { preview: review.approvals.clips.g001.final };
fs.writeFileSync(reviewFile, JSON.stringify(review));
assert.equal(approvalStatus(legacy, 'clip', [legacyVideo], 'g001').ok, false);
assert.throws(() => requireAllClips(legacy, { units: [{ id: 'g001' }] }), /尚未人工确认/);
console.log('human gates: passed');
